// Build runner for the Novakid token pipeline demo.
// Registers the two custom output formats, then builds all platforms from
// style-dictionary.config.mjs. Run via `npm run build:tokens`.
//
// Pipeline position:  tokens/tokens.json  ->  Style Dictionary  ->  build/{css,dart,ts}
// tokens.json is the file Tokens Studio pushes from Figma; this step is Phase 1
// (code side). Outputs are GENERATED, never hand-edited.

import StyleDictionary from 'style-dictionary';
import config from './style-dictionary.config.mjs';

const resolved = (t) => t.$value ?? t.value; // SD v4 puts the resolved value on $value (DTCG)
const typeOf = (t) => t.$type ?? t.type;

// ---- Unwrap the single token set ----------------------------------------
// tokens.json wraps everything in ONE set ("global") so Tokens Studio keeps it
// as a single set and {color.*} aliases resolve in-plugin (TS turns top-level
// keys into separate sets, which would strip the `color.` prefix and break the
// aliases). Style Dictionary doesn't want that wrapper in the token path, so we
// hoist `global` back to the root before processing — output names (`--nk-color-…`)
// and resolved hexes are identical to the unwrapped tree.
StyleDictionary.registerPreprocessor({
  name: 'nk/unwrap-global',
  preprocessor: (dictionary) => dictionary.global ?? dictionary,
});

// ---- Dimensions: bare number in source -> px on output ------------------
// The Figma name stores a bare number ("the platform renders the unit"); this
// transform appends px for CSS/TS. Colours, numbers (opacity), and fontWeight
// are untouched. transitive so it runs after any reference resolves.
StyleDictionary.registerTransform({
  name: 'nk/size-px',
  type: 'value',
  transitive: true,
  filter: (token) => typeOf(token) === 'dimension',
  transform: (token) => `${resolved(token)}px`,
});

// ---- Mobile: Flutter/Dart -----------------------------------------------
// Emits a NkColors class of `static const Color` fields. Only color/* tokens
// (primitives + semantic aliases) are emitted; aliases are already resolved to
// the primitive hex by Style Dictionary.
StyleDictionary.registerFormat({
  name: 'nk/dart-colors',
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens.filter(
      (t) => typeOf(t) === 'color' && t.path[0] === 'color',
    );
    const fields = colors
      .map((t) => {
        const hex = String(resolved(t)).replace('#', '').toUpperCase();
        return `  static const Color ${t.name} = Color(0xFF${hex});`;
      })
      .join('\n');
    return `// GENERATED by Style Dictionary — do not edit by hand.
// Source: Novakid Foundations tokens.json (Tokens Studio -> Git).
import 'dart:ui';

class NkColors {
  NkColors._();

${fields}
}
`;
  },
});

// ---- TypeScript: typed nested tree --------------------------------------
// Rebuilds the token tree as a plain nested object with resolved values, so
// callers get `tokens.color.background.brand.default` with full type inference.
StyleDictionary.registerFormat({
  name: 'nk/ts-nested',
  format: ({ dictionary }) => {
    const root = {};
    for (const t of dictionary.allTokens) {
      let node = root;
      t.path.forEach((seg, i) => {
        if (i === t.path.length - 1) node[seg] = resolved(t);
        else node = node[seg] ??= {};
      });
    }
    return `// GENERATED by Style Dictionary — do not edit by hand.
// Typed Novakid token tree. Example: tokens.color.background.brand.default
export const tokens = ${JSON.stringify(root, null, 2)} as const;

export type NkTokens = typeof tokens;
`;
  },
});

const sd = new StyleDictionary(config);
await sd.cleanAllPlatforms().catch(() => {});
await sd.buildAllPlatforms();
console.log('✓ Tokens built → build/css/variables.css, build/dart/nk_colors.dart, build/ts/tokens.ts');
